services:
    rmcgirr83.annualstar.listener:
        class: rmcgirr83\annualstar\event\listener
        arguments:
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
 